const projects = [
  {
    id: "coco_salvaje",
    title: "Coco Salvaje",
    summary: "Colombian natural skincare brand with Shopify and Amazon storefronts.",
    description: "Coco Salvaje is a skin care company based in Colombia who ship their products throughout their country and the United States through their e-commerce store on Shopify and Amazon.",
    image: "/images/projects/business_logos/coco_salvaje.jpg",
    page_images: ["/images/projects/business_pages/cocosalvajeco_website.png", "/images/projects/business_pages/cocosalvajecom_website.png"],
    techStack: [
      "JavaScript",
      "Liquid",
      "HTML",
      "CSS",
      "Shopify",
      "WordPress",
      "WooCommerce"
    ],
    link: "/projects/coco_salvaje",
    github: "",
    figma: [],
    live: "",
    demo: "",
    type: "Professional Work",
  },
  {
    id: "hacienda_mobile_home_sales",
    title: "Hacienda Mobile Home Sales",
    summary: "Mobile home real estate website redesign and PHP/MySQL to WiX migration.",
    description: "Hacienda Mobile Home Sales is a mobile home real estate company that contracted me to redesign their company website; migrating from a legacy PHP/MySQL website to the WiX CMS.",
    image: "/images/projects/business_logos/hacienda.jpg",
    page_images: ["/images/projects/business_pages/hacienda_website.png"],
    techStack: [
      "JavaScript",
      "PHP",
      "MySQL",
      "HTML",
      "CSS",
      "WIX"
    ],
    link: "/projects/hacienda_mobile_home_sales",
    github: "",
    figma: [],
    live: "",
    demo: "",
    type: "Professional Work",
  },
  {
    id: "blue_and_gold_clothing",
    title: "Blue & Gold Clothing",
    summary: "E-commerce apparel store built with Shopify CMS.",
    description: "Blue & Gold Clothing is an online apparel startup company who entrusted me to develop their website and set up a CRM/CMS via the Shopify platform.",
    image: "/images/projects/business_logos/blue_gold_clothing.jpg",
    page_images: ["/images/projects/business_pages/bgclothing_website.png"],
    techStack: [
      "JavaScript",
      "Liquid",
      "HTML",
      "CSS",
      "Shopify",
    ],
    link: "/projects/blue_and_gold_clothing",
    github: "",
    figma: [],
    live: "",
    demo: "",
    type: "Professional Work",
  },
  {
    id: "slate_prints",
    title: "Slate Prints",
    summary: "Custom Shopify storefront for personalized gift business.",
    description: "Slate Prints is an online e-commerce store with customizable products who contracted me to bring their vision to life with a modern website design and set up an CRM/CMS via Shopify.",
    image: "/images/projects/business_logos/slate_prints.jpg",
    page_images: ["/images/projects/business_pages/slate_prints_website.png"],
    techStack: [
      "JavaScript",
      "Liquid",
      "HTML",
      "CSS",
      "Shopify",
    ],
    link: "/projects/slate_prints",
    github: "",
    figma: [],
    live: "",
    demo: "",
    type: "Professional Work",
  },
  {
    id: "classic_barbershop",
    title: "Classic Barbershop",
    summary: "Barbershop website upgrade with improved SEO.",
    description: "Classic Barbershop is a local barbershop who contracted me to enhance their online presence by updating their website design, improving SEO, managing their Google Business Profile, running Google ads and optimizing their social media for Facebook and Instagram.",
    image: "/images/projects/business_logos/classic_barbershop.png",
    page_images: ["/images/projects/business_pages/classic_barbershop_website.jpg"],
    techStack: [
      "JavaScript",
      "HTML",
      "CSS",
      "Squarespace",
    ],
    link: "/projects/classic_barbershop",
    github: "",
    figma: [],
    live: "https://weslacoclassic.com/",
    demo: "",
    type: "Professional Work",
  },
  {
    id: "game_of_life",
    title: "Conway's Game of Life",
    summary: "C++ cellular automaton with interactive GUI.",
    description: "A C++ implementation of Conway's Game of Life, featuring a GUI built with wxWidgets. The project simulates the evolution of a cellular automaton based on simple rules and allows users to interact with the game through an intuitive graphical interface.",
    image: "/images/projects/project_logos/conways_game_of_life.png",
    page_images: [],
    techStack: [
      "C++",
      "wxWidgets",
    ],
    link: "/projects/game_of_life",
    github: "https://github.com/alvarotorrestx/conways_gameoflife",
    figma: [],
    live: "",
    demo: "https://www.youtube.com/embed/7Q-abV76SLw?si=57_o-e9tX6ZqwuWc",
    type: "Academic Projects",
  },
  {
    id: "simulint_innovations",
    title: "Simulint Innovations",
    summary: "Digital agency delivering web and marketing solutions.",
    description: "Simulint Innovations is a digital solutions agency with a mission to deliver tailored web design, development, and digital marketing services.",
    image: "/images/projects/business_logos/simulint_innovations.jpg",
    page_images: ["/images/projects/business_pages/simulint_innovations_website.jpg"],
    techStack: [
      "React",
      "JavaScript",
      "HTML",
      "CSS",
      "Webflow",
      "WiX",
      "Shopify",
      "WordPress",
      "Squarespace",
    ],
    link: "/projects/simulint_innovations",
    github: "",
    figma: [],
    live: "",
    demo: "",
    type: "Professional Work",
  },
  {
    id: "scientific_calculator",
    title: "Scientific Calculator",
    summary: "Custom calculator with singleton button factory pattern in C++.",
    description: "A scientific calculator application that provides an interactive GUI with dynamically created buttons using a Singleton Pattern Button Factory, allowing for a flexible and scalable design.",
    image: "/images/projects/project_logos/scientific_calculator.jpg",
    page_images: ["/images/projects/project_pages/scientific_calculator_default.png", "/images/projects/project_pages/scientific_calculator_result.png", "/images/projects/project_pages/scientific_calculator_pemdas.png", "/images/projects/project_pages/scientific_calculator_pemdas_result.png"],
    techStack: [
      "C++",
      "wxWidgets",
    ],
    link: "/projects/scientific_calculator",
    github: "https://github.com/alvarotorrestx/scientific_calculator",
    figma: [],
    live: "",
    demo: "",
    type: "Academic Projects",
  },
  {
    id: "heroic_organizer",
    title: "Heroic Organizer",
    summary: "Android app using ML to organize comic book collections.",
    description: "Heroic Organizer is an Android app built using Java and Firebase for comic book collectors and enthusiasts. The app has the ability to identify comics using barcode scanning (powered by Google’s ML Kit) and cover image scanning with metadata retrieval using Machine Learning (Weaviate).",
    image: "/images/projects/project_logos/heroic_organizer.png",
    page_images: [],
    techStack: [
      "Java",
      "Firebase",
      "Firestore",
      "Google ML Kit",
      "Weaviate",
    ],
    link: "/projects/heroic_organizer",
    github: "https://github.com/alvarotorrestx/heroic_organizer",
    figma: ["https://embed.figma.com/design/aSTbisZGgKvBwP9mSgj3sA/Heroic-Organizer---Wireframe?node-id=2-3&embed-host=share", "https://embed.figma.com/proto/iJ5k59C5FLbkn0bM3adI5q/Heroic-Organizer---Wireframe?node-id=2-3341&starting-point-node-id=2%3A3341&embed-host=share"],
    live: "",
    demo: "",
    type: "Professional Work",
  },
  {
    id: "devconnect",
    title: "DevConnect",
    summary: "Open-source MERN full-stack platform for developers to network.",
    description: "DevConnect is a developer-first networking platform designed to help engineers connect, collaborate, and share opportunities. The platform is an open-source MERN full-stack build for developers that supports scalable role-based access control, authentication, and contributor collaboration.",
    image: "/images/projects/project_logos/devconnect.png",
    page_images: ["/images/projects/project_pages/devconnect_light_dashboard.jpg", "/images/projects/project_pages/devconnect_dark_dashboard.jpg", "/images/projects/project_pages/devconnect_light_profile.jpg"],
    techStack: [
      "React",
      "JavaScript",
      "Express.js",
      "Node.js",
      "MongoDB",
      "JWT",
      "TailwindCSS",
      "Vite",
    ],
    link: "/projects/devconnect",
    github: "https://github.com/alvarotorrestx/devconnect",
    figma: [],
    live: "",
    demo: "",
    type: "Professional Work",
  },
  {
    id: "portfolio_next",
    title: "Portfolio",
    summary: "Personal developer portfolio built with modern frameworks and UI libraries.",
    description: "A sleek, one-page developer portfolio showcasing my work, experience, and skills. Built using Next.js, TypeScript, and TailwindCSS, it features smooth scroll animations with Framer Motion, responsive design, and dynamic sections powered by structured data for projects and experience.",
    image: "/images/projects/project_logos/portfolio.jpg",
    page_images: ["/images/projects/project_pages/portfolio_header.png", "/images/projects/project_pages/portfolio_skills.png", "/images/projects/project_pages/portfolio_experience.png", "/images/projects/project_pages/portfolio_projects.png", "/images/projects/project_pages/portfolio_contact.png"],
    techStack: [
      "Next.js",
      "React",
      "TypeScript",
      "JavaScript",
      "Node.js",
      "TailwindCSS",
      "DaisyUI",
      "Framer Motion",
    ],
    link: "/projects/portfolio_next",
    github: "https://github.com/alvarotorrestx/portfolio_next",
    figma: [],
    live: "https://alvarotorres.dev/",
    demo: "",
    type: "Professional Work",
  },
];

export default projects;
