const projects = [
  {
    id: "coco_salvaje",
    title: "Coco Salvaje",
    summary: "Shopify and WooCommerce storefronts for an international skincare brand.",
    description:
      "Developed and supported e-commerce storefronts for a Colombian skincare brand selling in Colombia and the United States. Worked across Shopify, WordPress, WooCommerce, and Amazon storefront workflows to support online sales and product visibility.",
    image: "/images/projects/business_logos/coco_salvaje.jpg",
    page_images: ["/images/projects/business_pages/cocosalvajeco_website.png", "/images/projects/business_pages/cocosalvajecom_website.png"],
    techStack: ["JavaScript", "Liquid", "HTML", "CSS", "Shopify", "WordPress", "WooCommerce", "Amazon"],
    link: "/projects/coco_salvaje",
    github: "",
    figma: [],
    live: "",
    demo: "",
    type: "Client Work",
    featuredOrder: 5,
  },
  {
    id: "hacienda_mobile_home_sales",
    title: "Hacienda Mobile Home Sales",
    summary: "Legacy PHP/MySQL website migration and inventory workflow automation.",
    description:
      "Redesigned and migrated a legacy PHP/MySQL website to Wix for a mobile home sales company, improving maintainability for non-technical staff and streamlining website updates. Also built Excel VBA automation to transform inventory data into JSON for live website updates.",
    image: "/images/projects/business_logos/hacienda.jpg",
    page_images: ["/images/projects/business_pages/hacienda_website.png"],
    techStack: ["JavaScript", "PHP", "MySQL", "HTML", "CSS", "Wix", "Velo", "Excel VBA", "JSON"],
    link: "/projects/hacienda_mobile_home_sales",
    github: "",
    figma: [],
    live: "",
    demo: "",
    type: "Client Work",
    featuredOrder: 1,
  },
  {
    id: "blue_and_gold_clothing",
    title: "Blue & Gold Clothing",
    summary: "Shopify e-commerce platform for an apparel startup.",
    description:
      "Developed and launched a Shopify-based e-commerce platform for an apparel startup, implementing storefront customization, product management workflows, CRM/CMS configuration, and customer-facing shopping features.",
    image: "/images/projects/business_logos/blue_gold_clothing.jpg",
    page_images: ["/images/projects/business_pages/bgclothing_website.png"],
    techStack: ["JavaScript", "Liquid", "HTML", "CSS", "Shopify", "CRM/CMS"],
    link: "/projects/blue_and_gold_clothing",
    github: "",
    figma: [],
    live: "",
    demo: "",
    type: "Client Work",
    featuredOrder: 4,
  },
  {
    id: "slate_prints",
    title: "Slate Prints",
    summary: "Shopify storefront for a personalized gift and printing business.",
    description:
      "Designed and deployed a Shopify-based e-commerce platform for a custom printing business, implementing storefront management, product configuration, CRM/CMS workflows, and online ordering capabilities.",
    image: "/images/projects/business_logos/slate_prints.jpg",
    page_images: ["/images/projects/business_pages/slate_prints_website.png"],
    techStack: ["JavaScript", "Liquid", "HTML", "CSS", "Shopify", "CRM/CMS"],
    link: "/projects/slate_prints",
    github: "",
    figma: [],
    live: "",
    demo: "",
    type: "Client Work",
    featuredOrder: 3,
  },
  {
    id: "classic_barbershop",
    title: "Classic Barbershop",
    summary: "Local business website, SEO, and Google Ads optimization.",
    description:
      "Enhanced the online presence of a local barbershop through website improvements, SEO optimization, Google Business Profile management, digital advertising, and social media updates to improve local visibility and customer engagement.",
    image: "/images/projects/business_logos/classic_barbershop.png",
    page_images: ["/images/projects/business_pages/classic_barbershop_website.jpg"],
    techStack: ["JavaScript", "HTML", "CSS", "Squarespace", "SEO", "Google Ads"],
    link: "/projects/classic_barbershop",
    github: "",
    figma: [],
    live: "https://weslacoclassic.com/",
    demo: "",
    type: "Client Work",
    featuredOrder: 2,
  },
  {
    id: "game_of_life",
    title: "Conway's Game of Life",
    summary: "C++ cellular automata simulation with an interactive wxWidgets GUI.",
    description:
      "C++ implementation of Conway's Game of Life featuring a wxWidgets graphical interface, interactive controls, and real-time cellular automata simulation based on configurable rule sets.",
    image: "/images/projects/project_logos/conways_game_of_life.png",
    page_images: [],
    techStack: ["C++", "wxWidgets", "OOP", "Simulation"],
    link: "/projects/game_of_life",
    github: "https://github.com/alvarotorrestx/conways_gameoflife",
    figma: [],
    live: "",
    demo: "https://www.youtube.com/embed/7Q-abV76SLw?si=57_o-e9tX6ZqwuWc",
    type: "Academic Projects",
    featuredOrder: 2,
  },
  {
    id: "simulint_innovations",
    title: "Simulint Innovations",
    summary: "Freelance web development and digital solutions business.",
    description:
      "Freelance web development and digital solutions business focused on helping small businesses improve their online presence through custom websites, CMS builds, lead capture workflows, API integrations, SEO improvements, and performance optimization.",
    image: "/images/projects/business_logos/simulint_innovations.jpg",
    page_images: ["/images/projects/business_pages/simulint_innovations_website.jpg"],
    techStack: ["JavaScript", "HTML", "CSS", "Webflow", "Wix", "Shopify", "WordPress", "Squarespace", "SEO", "API Integrations"],
    link: "/projects/simulint_innovations",
    github: "",
    figma: [],
    live: "",
    demo: "",
    type: "Client Work",
    featuredOrder: 6,
  },
  {
    id: "scientific_calculator",
    title: "Scientific Calculator",
    summary: "C++ desktop calculator using Singleton and Factory design patterns.",
    description:
      "Desktop scientific calculator built in C++ with wxWidgets, using Singleton and Factory design patterns to generate reusable button components and support a modular GUI architecture.",
    image: "/images/projects/project_logos/scientific_calculator.jpg",
    page_images: ["/images/projects/project_pages/scientific_calculator_default.png", "/images/projects/project_pages/scientific_calculator_result.png", "/images/projects/project_pages/scientific_calculator_pemdas.png", "/images/projects/project_pages/scientific_calculator_pemdas_result.png"],
    techStack: ["C++", "wxWidgets", "OOP", "Design Patterns"],
    link: "/projects/scientific_calculator",
    github: "https://github.com/alvarotorrestx/scientific_calculator",
    figma: [],
    live: "",
    demo: "",
    type: "Academic Projects",
    featuredOrder: 1,
  },
  {
    id: "heroic_organizer",
    title: "Heroic Organizer",
    summary: "Android app using ML-powered scanning to organize comic book collections.",
    description:
      "Heroic Organizer is an Android application built for comic book collectors using Java, Firebase, Firestore, Google ML Kit, and Weaviate. The app supports barcode scanning, image-based comic identification, and metadata retrieval workflows to help users catalog and manage their collections.",
    image: "/images/projects/project_logos/heroic_organizer.png",
    page_images: [],
    techStack: ["Java", "Firebase", "Firestore", "Google ML Kit", "Weaviate"],
    link: "/projects/heroic_organizer",
    github: "https://github.com/alvarotorrestx/heroic_organizer",
    figma: ["https://embed.figma.com/design/aSTbisZGgKvBwP9mSgj3sA/Heroic-Organizer---Wireframe?node-id=2-3&embed-host=share", "https://embed.figma.com/proto/iJ5k59C5FLbkn0bM3adI5q/Heroic-Organizer---Wireframe?node-id=2-3341&starting-point-node-id=2%3A3341&embed-host=share"],
    live: "",
    demo: "",
    type: "Featured Projects",
    featuredOrder: 5,
  },
  {
    id: "devconnect",
    title: "DevConnect",
    summary: "Open-source MERN platform for developers to connect, collaborate, and share opportunities.",
    description:
      "DevConnect is an open-source MERN platform built to help developers connect, collaborate, and share opportunities. It features role-based access control, JWT authentication, contributor workflows, and scalable backend services while supporting collaboration across a community of 11+ contributors through GitHub and Discord.",
    image: "/images/projects/project_logos/devconnect.png",
    page_images: ["/images/projects/project_pages/devconnect_light_dashboard.jpg", "/images/projects/project_pages/devconnect_dark_dashboard.jpg", "/images/projects/project_pages/devconnect_light_profile.jpg"],
    techStack: [
      "React",
      "JavaScript",
      "Express.js",
      "Node.js",
      "MongoDB",
      "JWT",
      "TailwindCSS",
      "Vite",
    ],
    link: "/projects/devconnect",
    github: "https://github.com/alvarotorrestx/devconnect",
    figma: [],
    live: "",
    demo: "",
    type: "Featured Projects",
    featuredOrder: 4,
  },
  {
    id: "portfolio_next",
    title: "Portfolio",
    summary: "Personal developer portfolio built with modern frameworks and UI libraries.",
    description: "A sleek, one-page developer portfolio showcasing my work, experience, and skills. Built using Next.js, TypeScript, and TailwindCSS, it features smooth scroll animations with Framer Motion, responsive design, and dynamic sections powered by structured data for projects and experience.",
    image: "/images/projects/project_logos/portfolio.jpg",
    page_images: ["/images/projects/project_pages/portfolio_header.png", "/images/projects/project_pages/portfolio_skills.png", "/images/projects/project_pages/portfolio_experience.png", "/images/projects/project_pages/portfolio_projects.png", "/images/projects/project_pages/portfolio_contact.png"],
    techStack: [
      "Next.js",
      "React",
      "TypeScript",
      "JavaScript",
      "Node.js",
      "TailwindCSS",
      "DaisyUI",
      "Framer Motion",
    ],
    link: "/projects/portfolio_next",
    github: "https://github.com/alvarotorrestx/portfolio_next",
    figma: [],
    live: "https://alvarotorres.dev/",
    demo: "",
    type: "Professional Work",
  },
  {
    id: "skipapi",
    title: "SkipAPI",
    summary: "AI-powered SaaS platform that turns natural language prompts into backend API foundations.",
    description:
      "SkipAPI is an AI-powered SaaS platform that transforms natural language prompts into backend API foundations, helping developers accelerate application development and reduce repetitive setup work. Built with Next.js, TypeScript, Express.js, MongoDB, Redis, and OpenAI.",
    image: "/images/projects/project_logos/ai_laptop.jpg",
    page_images: ["/images/projects/project_pages/skipapi_landing.png", "/images/projects/project_pages/skipapi_app.png"],
    techStack: [
      "Next.js",
      "TypeScript",
      "React",
      "Node.js",
      "Express.js",
      "OpenAI",
      "Redis",
      "MongoDB",
      "JWT",
      "TailwindCSS",
    ],
    link: "/projects/skipapi",
    github: "",
    figma: [],
    live: "",
    demo: "",
    type: "Featured Projects",
    featuredOrder: 3,
  },
  {
    id: "pulsedesk",
    title: "PulseDesk",
    summary: "AI-powered call intelligence platform for contact center analytics, compliance review, and coaching insights.",
    description:
      "PulseDesk is an AI-powered call intelligence platform developed to demonstrate contact center analytics and automation use cases for Finance of America technology leadership. It processes call audio and transcripts using Whisper-based transcription, rule-based compliance scoring, and alerting workflows to identify sentiment trends, compliance risks, coaching opportunities, and operational issues.",
    image: "/images/projects/project_logos/pulsedesk.jpg",
    page_images: [],
    techStack: [
      "React",
      "TypeScript",
      "Python",
      "FastAPI",
      "PostgreSQL",
      "Whisper",
      "Rule Engine",
      "TailwindCSS",
      "DaisyUI"
    ],
    link: "/projects/pulsedesk",
    github: "",
    figma: [],
    live: "",
    demo: "https://www.youtube.com/embed/inzRd_qKO38?si=qRPD0ijcaYitXCyU",
    type: "Featured Projects",
    featuredOrder: 2,
  },
  {
    id: "classmateai",
    title: "ClassmateAI",
    summary: "Full-stack AI study platform that turns uploaded documents into notes, flashcards, quizzes, and study guides.",
    description:
      "ClassmateAI is a full-stack AI study platform built to help students transform course materials into personalized study content. Users can upload documents and generate AI-powered notes, flashcards, quizzes, and study guides while tracking progress through analytics, gamification, export, and public sharing features.",
    image: "/images/projects/project_logos/classmateai.png",
    page_images: [],
    techStack: [
      "React",
      "TailwindCSS",
      "Python",
      "FastAPI",
      "PostgreSQL",
      "SQLAlchemy",
      "Gemini AI",
      "JWT",
    ],
    link: "/projects/classmateai",
    github: "https://github.com/alvarotorrestx/classmateai",
    figma: [],
    live: "https://classmateai-five.vercel.app/",
    demo: "",
    type: "Featured Projects",
    featuredOrder: 1,
  },
];

export default projects;
