const projects = [
  {
    id: "coco_salvaje",
    title: "Coco Salvaje",
    description: "Coco Salvaje is a skin care company based in Colombia who ship their products throughout their country and the United States through their e-commerce store on Shopify and Amazon.",
    image: "/images/projects/business_logos/coco_salvaje.jpg",
    techStack: [
      "JavaScript",
      "Liquid",
      "HTML",
      "CSS",
      "Shopify",
      "WordPress",
      "WooCommerce"
    ],
    link: "",
    type: "Client Work",
  },
  {
    id: "hacienda_mobile_home_sales",
    title: "Hacienda Mobile Home Sales",
    description: "Hacienda Mobile Home Sales is a mobile home real estate company that contracted me to redesign their company website; migrating from a legacy PHP/MySQL website to the WiX CMS.",
    image: "/images/projects/business_logos/hacienda.jpg",
    techStack: [
      "JavaScript",
      "PHP",
      "MySQL",
      "HTML",
      "CSS",
      "WIX"
    ],
    link: "",
    type: "Client Work",
  },
  {
    id: "blue_and_gold_clothing",
    title: "Blue & Gold Clothing",
    description: "Blue & Gold Clothing is an online apparel startup company who entrusted me to develop their website and set up a CRM/CMS via the Shopify platform.",
    image: "/images/projects/business_logos/blue_gold_clothing.jpg",
    techStack: [
      "JavaScript",
      "Liquid",
      "HTML",
      "CSS",
      "Shopify",
    ],
    link: "",
    type: "Client Work",
  },
  {
    id: "slate_prints",
    title: "Slate Prints",
    description: "Slate Prints is an online e-commerce store with customizable products who contracted me to bring their vision to life with a modern website design and set up an CRM/CMS via Shopify.",
    image: "/images/projects/business_logos/slate_prints.jpg",
    techStack: [
      "JavaScript",
      "Liquid",
      "HTML",
      "CSS",
      "Shopify",
    ],
    link: "",
    type: "Client Work",
  },
  {
    id: "classic_barbershop",
    title: "Classic Barbershop",
    description: "Classic Barbershop is a local barbershop who contracted me to enhance their online presence by updating their website design, improving SEO, managing their Google Business Profile, running Google ads and optimizing their social media for Facebook and Instagram.",
    image: "/images/projects/business_logos/classic_barbershop.png",
    techStack: [
      "JavaScript",
      "HTML",
      "CSS",
      "Squarespace",
    ],
    link: "",
    type: "Client Work",
  },
  {
    id: "game_of_life",
    title: "Conway's Game of Life",
    description: "A C++ implementation of Conway's Game of Life, featuring a GUI built with wxWidgets. The project simulates the evolution of a cellular automaton based on simple rules and allows users to interact with the game through an intuitive graphical interface.",
    image: "/images/projects/project_logos/conways_game_of_life.png",
    techStack: [
      "C++",
      "wxWidgets",
    ],
    link: "",
    type: "School Projects",
  },
  {
    id: "simulint_innovations",
    title: "Simulint Innovations",
    description: "Simulint Innovations is a digital solutions agency with a mission to deliver tailored web design, development, and digital marketing services.",
    image: "/images/projects/business_logos/simulint_innovations.jpg",
    techStack: [
      "React",
      "JavaScript",
      "HTML",
      "CSS",
      "Webflow",
      "WiX",
      "Shopify",
      "WordPress",
      "Squarespace",
    ],
    link: "",
    type: "Client Work",
  },
  {
    id: "scientific_calculator",
    title: "Scientific Calculator",
    description: "A scientific calculator application that provides an interactive GUI with dynamically created buttons using a Singleton Pattern Button Factory, allowing for a flexible and scalable design.",
    image: "/images/projects/project_logos/scientific_calculator.jpg",
    techStack: [
      "C++",
      "wxWidgets",
    ],
    link: "",
    type: "School Projects",
  },
  {
    id: "heroic_organizer",
    title: "Heroic Organizer",
    description: "Heroic Organizer is an Android app built using Java and Firebase for comic book collectors and enthusiasts. The app has the ability to identify comics using barcode scanning (powered by Google’s ML Kit) and cover image scanning with metadata retrieval using Machine Learning (Weaviate).",
    image: "/images/projects/project_logos/heroic_organizer.png",
    techStack: [
      "Java",
      "Firebase",
      "Firestore",
      "Google ML Kit",
      "Weaviate",
    ],
    link: "",
    type: "Projects",
  },
  {
    id: "devconnect",
    title: "DevConnect",
    description: "DevConnect is a developer-first networking platform designed to help engineers connect, collaborate, and share opportunities. The platform is an open-source MERN stack networking platform for developers that supports scalable role-based access control, authentication, and contributor collaboration.",
    image: "/images/projects/project_logos/devconnect.png",
    techStack: [
      "React",
      "JavaScript",
      "Express.js",
      "Node.js",
      "MongoDB",
      "JWT",
      "TailwindCSS",
      "Vite",
    ],
    link: "",
    type: "Projects",
  },
];

export default projects;
